# Generated by Django 4.2.6 on 2024-12-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
                ('details_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('salary', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
