# Generated by Django 4.2.6 on 2024-12-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0003_remove_job_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='posted_date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
