# Generated by Django 4.2.6 on 2024-12-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0004_alter_job_posted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='updated_date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
