# Generated by Django 4.2.6 on 2024-12-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0005_job_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skill',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
